export const ICON_LIST = [
  '2 User',
  '3 User',
  'Activity',
  'Add User',
  'Arrow - Down 2',
  'Arrow - Down 3',
  'Arrow - Down Circle',
  'Arrow - Down Square',
  'Arrow - Down',
  'Arrow - Left 2',
  'Arrow - Left 3',
  'Arrow - Left Circle',
  'Arrow - Left Square',
  'Arrow - Left',
  'Arrow - Right 2',
  'Arrow - Right 3',
  'Arrow - Right Circle',
  'Arrow - Right Square',
  'Arrow - Right',
  'Arrow - Up 2',
  'Arrow - Up 3',
  'Arrow - Up Circle',
  'Arrow - Up Square',
  'Arrow - Up',
  'Bag 2',
  'Bag',
  'Bookmark',
  'Buy',
  'Calendar',
  'Call Missed',
  'Call Silent',
  'Call',
  'Calling',
  'Camera',
  'Category',
  'Chart',
  'Chat',
  'Close Square',
  'Danger',
  'Dark',
  'Delete',
  'Discount',
  'Discovery',
  'Document',
  'Download',
  'Edit Square',
  'Edit',
  'Filter 2',
  'Filter',
  'Folder',
  'Game',
  'Graph',
  'Heart',
  'Hide',
  'Home',
  'Image 2',
  'Image',
  'Info Circle',
  'Info Square',
  'Location',
  'Lock',
  'Login',
  'Logout',
  'Message',
  'More Circle',
  'More Square',
  'Notification',
  'Paper Download',
  'Paper Fail',
  'Paper Negative',
  'Paper Plus',
  'Paper Upload',
  'Paper',
  'Password',
  'Play',
  'Plus',
  'Profile',
  'Scan',
  'Search',
  'Send',
  'Setting',
  'Shield Done',
  'Shield Fail',
  'Show',
  'Star',
  'Swap',
  'Tick Square',
  'Ticket Star',
  'Ticket',
  'Time Circle',
  'Time Square',
  'Unlock',
  'Upload',
  'Video',
  'Voice 2',
  'Voice',
  'Volume Down',
  'Volume Off',
  'Volume Up',
  'Wallet',
  'Work',
];
export const COLOR_LIST = [
  'gradient-green',
  'gradient-yellow',
  'gradient-blue',
  'gradient-red',
  'gradient-purple',
  'gradient-teal',
  'gradient-orange',
];
